### ISSUE TITLE
scripts on CDN

### ISSUE THREAD

**Issue by danlaquarium** [shaka-project/eme-encryption-scheme-polyfill#53]
Can both EME & MC polyfills scripts be loaded on CDNJS, JSdeliver or another CDN? It would be nice, because our node-modules folder isn't available to the public. so NPMing these files locally doesn't help us for that matter.

**Comment by joeyparrish** [comment]
Yes, absolutely.

We put Shaka Player on CDNJS, and it was a painful manual effort that required updating when paths in the library changed.  Even forking/cloning the CDNJS repo to make updates is extremely difficult because of its size.  Often the connection is aborted during the GitHub fork process, and you then have to push updates in chunks just to get your fork in sync with upstream before you make a PR... It's a nightmare.  So there is **0** chance I will make the effort to put this library into CDNJS.

The other CDNs, though, should just work.  JSDelivr, unpkg, etc, don't require any setup, and are already serving this library.  For example:

 - https://www.jsdelivr.com/package/npm/eme-encryption-scheme-polyfill
 - https://cdn.jsdelivr.net/npm/eme-encryption-scheme-polyfill@2.1.1/dist/eme-encryption-scheme-polyfill.js
 - https://unpkg.com/eme-encryption-scheme-polyfill@2.1.1/dist/eme-encryption-scheme-polyfill.js

Probably you can find it on other CDNs, as well.  (Just not CDNJS.)

Does this help?

**Comment by danlaquarium** [comment]
Hi Joey, that's awesome! I can certainly use those CDNs. Do you know if the same CDNs offer the libraries for the Mc Encryption Scheme Polyfill as well?

**Comment by joeyparrish** [comment]
That is all part of the same library.  All of the files from the NPM package are available on each CDN.
